Set CAKE_PATHS_TOOLS environment variable in build.ps1
cake-build/resources pull request #88
Opened 2020-11-02 22:38 UTC by LorianColtof

If you changed $TOOLS_DIR into something else then addins would still be installed in the tools directory. Setting this environment variable makes sure that Cake.exe also uses the right tools directory.

2020-11-02 22:44 UTC, pascalberger requested changes
To be consistent the environment variables should also be set in the `build.sh` bootstrapper.

2020-11-02 22:44 UTC, pascalberger commented on build.ps1
> +$env:CAKE_PATHS_TOOLS = $TOOLS_DIR
We should also set `CAKE_PATHS_ADDINS` and `CAKE_PATHS_MODULES` to the appropriate values

2020-11-03 20:19 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/cake-build/resources?pullRequest=88) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/cake-build/resources?pullRequest=88) before we can accept your contribution.<br/><br/>:x: LorianColtof [sign now](https://cla.dotnetfoundation.org/cake-build/resources?pullRequest=88)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/cake-build/resources?pullRequest=88) it.</sub>

2020-11-03 20:22 UTC, LorianColtof commented
I added all the missing environment variables.

2020-11-03 20:25 UTC, pascalberger approved these changes
LGTM

2020-11-03 20:35 UTC, gep13 approved these changes
LGTM!

2020-11-03 20:35 UTC, merged

2020-11-03 20:35 UTC, gep13 commented
@LorianColtof thanks for doing this, appreciate it!